name: python312-cpu
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - jupytext
  - jupyterlab
  - arviz
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - tensorflow
  - tensorflow-probability
  - xarray
  - pympler
  - statsmodels
  - jax
  - numpyro
  - nutpie
  - ipywidgets>=8.1.7,<9
  - memory_profiler>=0.61.0,<0.62
  - pymc==5.24.1
  - pymc-marketing>=0.15.1,<0.16
  - blackjax>=1.2.4,<2
  - great_tables>=0.18.0,<0.19
  - pip
  - pip:
      - google-meridian>=1.1.6,<2