[workspace]
authors = ["Thomas Wiecki <thomas.wiecki@gmail.com>"]
channels = ["conda-forge"]
name = "mmm-param-recovery"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pymc-marketing = ">=0.14.0,<0.15"
pytest = ">=8.4.1,<9"

[pypi-dependencies]
meridian = ">=0.4.0, <0.5"
ruff = ">=0.3.0"
pre-commit = ">=3.0.0"

