[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mmm-param-recovery"
version = "0.1.0"
description = "A package for generating synthetic MMM (Media Mix Modeling) datasets for parameter recovery studies"
authors = [{name = "Thomas Wiecki", email = "thomas.wiecki@gmail.com"}]
requires-python = ">=3.12"
dependencies = ["google-meridian>=1.1.6,<2"]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "pre-commit",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mmm_param_recovery*"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
mmm-param-recovery = { path = ".", editable = true }

[tool.pixi.dependencies]
pytest = "*"
ipykernel = "*"
jupytext = "*"
jupyterlab = "*"
arviz = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
pymc = "*"
seaborn = "*"
tensorflow = "*"
tensorflow-probability = "*"
xarray = "*"
pympler = "*"
statsmodels = "*"
pymc-marketing = "==0.15.0"
jax = ">=0.5.2,<0.6"
numpyro = ">=0.18.0,<0.19"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short" 
