[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mmm-param-recovery"
version = "0.1.0"
description = "A package for generating synthetic MMM (Media Mix Modeling) datasets for parameter recovery studies"
authors = [{name = "Thomas Wiecki", email = "thomas.wiecki@gmail.com"}]
requires-python = ">=3.12"
dependencies = ["google-meridian>=1.1.6,<2"]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "pre-commit",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mmm_param_recovery*"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
mmm-param-recovery = { path = ".", editable = true }

[tool.pixi.dependencies]
pytest = "*"
ipykernel = "*"
jupytext = "*"
jupyterlab = "*"
arviz = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
pymc = "*"
seaborn = "*"
tensorflow = "*"
tensorflow-probability = "*"
xarray = "*"
pympler = "*"
statsmodels = "*"
pymc-marketing = "==0.15.0"
jax = ">=0.5.2,<0.6"
numpyro = ">=0.18.0,<0.19"
nutpie = ">=0.15.2,<0.16"
ipywidgets = ">=8.1.7,<9"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short" 

[tool.pixi.tasks.make_test_data]
cmd = "python mmm_param_recovery/make_test_data.py --preset_name {{preset_name}} --seed {{seed}}"
args = ["preset_name", { arg = "seed", default = "42"}]
inputs = ["mmm_param_recovery/data_generator/*", "mmm_param_recovery/make_test_data.py"]
outputs = [
    "data/test_data/test_data_{{ preset_name}}_{{ seed }}.csv",
    "data/test_data/ground_truth_{{ preset_name}}_{{ seed }}.csv"
]

[tool.pixi.tasks.mmm_file_type]
args = ["mmm_library"]
cmd = """echo {% if "meridian" in mmm_library %}pkl{% else %}nc{% endif %}"""

[tool.pixi.tasks.fit_model]
args = ["mmm_library", "preset_name", { arg = "seed", default = "42"}]
cmd = "python mmm_param_recovery/fit_{{ mmm_library }}.py --preset_name {{ preset_name }} --seed {{ seed }}"    
inputs = ["data/test_data/test_data_{{ preset_name }}_{{ seed }}.csv"]
# output broken for some reason.
# outputs = ["data/fits/{{ mmm_library }}_{{ preset_name }}_{{ seed }}.$(pixi run mmm_file_type {{ mmm_library }})"]
depends-on = [{ "task" = "make_test_data", "args" = ["{{ preset_name }}", "{{ seed }}"] }]
